name: zephyr
description: "自动弹琴工具 - Auto Piano Player"
publish_to: 'none'
version: 1.0.0-beta.19+19

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.3.3
  file_picker: ^8.1.4
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "Zephyr.jpg"
  adaptive_icon_background: "#0F0F14"
  adaptive_icon_foreground: "Zephyr.jpg"
